# =============================================================================
# Kareus Development Docker Container
# =============================================================================
# 
# BUILD INSTRUCTIONS:
# Build the Docker image from the project root directory:
#   docker build -f .devcontainer/dockerfile.dev -t kareus-dev .
#
# RUN INSTRUCTIONS:
# Run the container with full configuration (equivalent to devcontainer.json):
#   docker run -it --rm \
#     --gpus=all \
#     --ipc=host \
#     --network=host \
#     --name=ruofan-kareus \
#     --privileged \
#     -v /dev/shm:/dev/shm \
#     -v $HOME/.cache/huggingface:/root/.cache/huggingface \
#     -v $HOME/.ssh:/root/.ssh \
#     -v $HOME/workspace:/workspaces \
#     -v $(pwd):/workspaces/Kareus \
#     kareus-dev
#
# docker exec -it --privileged ruofan-kareus bash
#
# SIMPLIFIED RUN (minimal configuration):
#   docker run -it --rm --gpus=all -v $(pwd):/workspaces/Kareus kareus-dev
#
# =============================================================================

# Use the NVIDIA PyTorch base image
FROM nvcr.io/nvidia/pytorch:24.12-py3

# Install git
RUN apt-get update && apt-get install -y wget libspdlog-dev libglib2.0-0 pigz nlohmann-json3-dev git zsh && rm -rf /var/lib/apt/lists/*

# Update pip to the latest version
RUN pip install --no-cache-dir --upgrade pip

# Uninstall apex first
RUN pip uninstall -y apex

RUN python -m pip install --upgrade pip
RUN pip install flash-attn==2.7.0.post2 --no-build-isolation

# Install NVIDIA apex from source
RUN git clone https://github.com/NVIDIA/apex && \
    cd apex && \
    pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext"  --config-settings "--build-option=--distributed_adam" --config-settings "--build-option=--distributed_lamb" --config-settings "--build-option=--deprecated_fused_adam" --config-settings "--build-option=--deprecated_fused_lamb" ./

RUN pip install --no-build-isolation 'transformer_engine[pytorch]'==2.4.0
RUN pip install 'megatron-core[dev]'==0.12.1
RUN pip install "nemo_toolkit[all]"==2.3.1
RUN pip install omegaconf
RUN pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu126
RUN pip install zeus

WORKDIR /workspaces/Kareus

# Install ffmpeg and libsm6 libxext6
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# make sure docker container has the correct ibverbs.so
RUN ln -s /usr/lib/x86_64-linux-gnu/libibverbs.so.1 /usr/lib/x86_64-linux-gnu/libibverbs.so

# Set default compiler environment variables
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++

# Set MPI compiler environment variables
ENV OMPI_CC=/usr/bin/gcc
ENV OMPI_CXX=/usr/bin/g++
ENV MPICH_CC=/usr/bin/gcc
ENV MPICH_CXX=/usr/bin/g++
ENV MPICC_CC=/usr/bin/gcc
ENV MPICXX_CXX=/usr/bin/g++

# Install oh-my-zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install powerlevel10k theme
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Install zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# download zsh-syntax-highlighting
RUN git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Configure zsh
# RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc && \
RUN sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc

# add zsh-completions to fpath
RUN echo 'fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src' >> ~/.zshrc

# Set zsh as default shell
ENV SHELL=/bin/zsh
CMD [ "zsh" ]

RUN git config --global user.name "Ruofan Wu"
RUN git config --global user.email "ruofanw@umich.edu"

